version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
        - /var/lib/mysql
    ports:
        - 3306:3306
    environment:
     MYSQL_ROOT_PASSWORD: salad_bot
     MYSQL_DATABASE: bot
     MYSQL_USER: bot
     MYSQL_PASSWORD: bot

  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: bot
    command: >
      sh -c '
            cd /usr/src/app;
            npm i; 
            npm run bot'
    volumes:
      - ./:/usr/src/app/
